# Generated by Django 3.1.1 on 2020-10-11 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('image_url', models.CharField(max_length=500)),
                ('color_code', models.CharField(max_length=20)),
                ('registered_on', models.DateTimeField()),
                ('is_active', models.BooleanField()),
            ],
        ),
    ]
