# Generated by Django 3.1.1 on 2020-10-31 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0003_cartitem'),
        ('payment_module', '0002_invoice_invoicedetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvoiceDetails',
            new_name='InvoiceDetail',
        ),
    ]
